### ISSUE TITLE
Does not remove the junk

### ISSUE THREAD

**Issue by ReallReaper** [DevT02/Junk-Remover#3]
- provide a video showing why it doesn't delete the junk:

**The video:** https://gofile.io/d/IQUbem

`I upload it to Gofiles because the video lasts 4 minutes and 40 seconds and github only leaves a 10mb video file haha`

**Comment by DevT02** [comment]
The reason why this doesn't remove that junk is because this tool is pretty old and only removed attributes through name only aka things like ``BabelObfuscator``, ``Goliath``, ``<ObfuscatedByDotNetPatcher>``. **This is because some methods could theoretically be invoked through reflection, thereby breaking the program**. However, DarksProtector's Junk is literally just random classes. Instead of needing a tool, you should just go into DnSpy and manually delete the files with a click and a shift-click plus delete. Another piece of advice: If you want, try modding this tool to best fit what you need (maybe look to see if an attribute starts with DarksProtector, delete?)

**Comment by DevT02** [comment]
Mod this:
https://github.com/DevT02/Junk-Remover/blob/f187c15a08c6bd3c95916278b4728b6e354f156f/JunkRemover/Program.cs#L128-L296

or this (whichever works):

https://github.com/DevT02/Junk-Remover/blob/f187c15a08c6bd3c95916278b4728b6e354f156f/JunkRemover/Program.cs#L312-L334
